services:
  radio-ripper:
    image: domoskanonos/radioripper:latest
    container_name: radio-ripper
    restart: unless-stopped
    volumes:
      - ./config:/app/config:ro
      - ./work:/app/work
      - ./recordings:/app/recordings
    stop_signal: SIGTERM
    stop_grace_period: 30s
